### PR TITLE
Standardize code comment format

### LINKED ISSUE #308: Standardize code comment format
## Problem

In some of the code in `R/` (and maybe `vignettes/`), a form of "ASCII art" was used to box the comments, looking like this:

```r
# ----------------------------#
#    check input values       #
# ----------------------------#
```

This format looks nice but might not be ideal for a few reasons:

- **Readability**: These comments are harder to read and write consistently. It will surely require extra effort to maintain the alignment of the boxes as the content of the comments change.
- **Searchability**: With a mixture of differently formatted boxes, code comments are harder to search and parse programmatically.
- **Portability**: The comments may not render properly in environments such as emails that do not support monospace fonts, where the box structure may not appear as intended.
- **Version control compatibility**: The more sophisticated formatting can complicate version control, making it harder to track changes and resolve conflicts in the long run.

---

## Proposed solution

Reformat the code comments with the standard format [tidyverse style guide](https://style.tidyverse.org/functions.html#comments-1). As I quote:

> Each line of a comment should begin with the comment symbol and a single space: `# `.
>
> Comments should be in sentence case, and only end with a full stop if they contain at least two sentences.

Also, if a section structure is needed, use the [standard convention](https://support.posit.co/hc/en-us/articles/200484568-Code-Folding-and-Sections-in-the-RStudio-IDE) that can be parsed in RStudio, preferably with trailing dashes (`-`):

> ... any comment line which includes at least four trailing dashes (`-`), equal signs (`=`), or pound signs (`#`) automatically creates a code section.

So, the above comment could become simply

```r
# Check input values ----
```

### PR DESCRIPTION
**Pull request by jdblischak**
Closes #308 

I ran the following code to reformat the code comments. Sometimes this added a newline above the comment, but I think this is probably a good thing since the point of the ASCII art was to make the comment stand out from the surrounding code

```R
library("stringr")
library("styler")

files <- list.files(pattern = "(.R|.Rmd)$", full.names = TRUE, recursive = TRUE)
pattern <- "\\s*# -+\\s#\\n\\s*#\\s*([^\\s].*?)\\s+#\\n\\s*# -+\\s#"
pattern_roxy <- "#'*\\s*# -+\\s#\\n#'\\s*#\\s*([^\\s].*?)\\s+#\\n#'\\s*# -+\\s#"
for (f in files) {
  lines_in <- readLines(f)
  lines_out <- paste(lines_in, collapse = "\n")
  lines_out <- str_replace_all(lines_out, pattern, "\n\n# \\1 ----")
  lines_out <- str_replace_all(lines_out, pattern_roxy, "#' # \\1 ----")
  writeLines(lines_out, con = f)
}
style_pkg()
```

### CODE REVIEW

**Comment by jdblischak** [comment]
Converted to a draft. My regex isn't capturing all of the comments yet

**Comment by jdblischak** [comment]
I've managed to reformat all the single-line comments. Waiting for guidance on how to update multi-line comments (https://github.com/Merck/gsDesign2/issues/308#issuecomment-1885746785)

Updated code to handle the cases where there are no spaces between the `#` and the `-`:

```R
library("devtools")
library("stringr")
library("styler")

files <- list.files(pattern = "(.R|.Rmd)$", full.names = TRUE, recursive = TRUE)
pattern <- "\\s*#\\s*-+\\s*#\\n\\s*#\\s*([^\\s].*?)\\s*#\\n\\s*#\\s*-+\\s*#"
pattern_roxy <- "#'*\\s*#\\s*-+\\s*#\\n#'\\s*#\\s*([^\\s].*?)\\s*#\\n#'\\s*#\\s*-+\\s*#"
for (f in files) {
  lines_in <- readLines(f)
  lines_out <- paste(lines_in, collapse = "\n")
  lines_out <- str_replace_all(lines_out, pattern, "\n\n# \\1 ----")
  lines_out <- str_replace_all(lines_out, pattern_roxy, "#' # \\1 ----")
  writeLines(lines_out, con = f)
}
style_pkg()
document()
```

**Comment by nanxstats** [comment]
Whoa, this is unreasonable nice and effective! I appreciate the code-based solution very much. 👍 

Could you do me a small favor and capitalize the first letter, too? From the [tidyverse style guide](https://style.tidyverse.org/functions.html#comments-1):

> Comments should be in sentence case, and only end with a full stop if they contain at least two sentences.

Note that acronyms like "AHR" "WLR" should be all capitalized.

For multi-line comments, I replied my opinion in #308. If it's too complicated to automate with code, you can try fix them manually and I hope there is not too many of them... 😬

**Comment by jdblischak** [comment]
> Could you do me a small favor and capitalize the first letter, too? 

This code got me most of the way there. I had to do a few manual edits afterwards to fix some acronyms


```R
# Convert comments to sentence case

library("stringr")

sentence_case <- function(x) {
  if (x == toupper(x)) return(x)
  str_to_sentence(x)
}

files <- list.files(pattern = "(.R|.Rmd)$", full.names = TRUE, recursive = TRUE)
pattern <- ".*#\\s.+\\s----$"
for (f in files) {
  lines_in <- readLines(f)
  lines_out <- str_replace_all(lines_in, pattern, sentence_case)
  writeLines(lines_out, con = f)
}
```

**Comment by jdblischak** [comment]
@nanxstats I've converted all the box comments. I fixed a few other comments that were not in sentence case. If you'd like everything single comment converted to sentence case, please open a new Issue for that task

**Review by nanxstats — APPROVED** [review]
Looking great! Let's merge this. Thanks so much for tidying up the code comments.

(The check error on r-devel is not relevant to this change - it's due to the GitHub Actions cache of Rcpp and can be figured out separately.)

**Pull request merged**
