### PR TITLE
update rd part

### PR DESCRIPTION
**Pull request by LittleBeannie**

### CODE REVIEW

**Review by nanxstats — CHANGES_REQUESTED** [review]
Please consider using `snake_case` for the option values of the enumerated type arguments per the [style guide](https://merck.github.io/gsDesign2/articles/style.html#enumerated-type-arguments).

```r
c("un_stratified", "ss", "invar_h1", "invar_h0")`
```

Also, should it just be `"unstratified"` or `"un_stratified"`? Because the former can be an actual word without a separator.

**Comment by LittleBeannie** [comment]
> Please consider using `snake_case` for the option values of the enumerated type arguments per the [style guide](https://merck.github.io/gsDesign2/articles/style.html#enumerated-type-arguments).
> 
> ```r
> c("un_stratified", "ss", "invar_h1", "invar_h0")`
> ```
> 
> Also, should it just be `"unstratified"` or `"un_stratified"`? Because the former can be an actual word without a separator.

Thanks for reminding me! Yes, let's use `"unstratified"` instead.

**Comment by LittleBeannie** [comment]
It is ready for merge @nanxstats , though there are still some remaining lint issues...

**Review by nanxstats — APPROVED** [review]
Now it passes!

**Pull request merged**
