### PR TITLE
Fix code linting issues

### PR DESCRIPTION
**Pull request by nanxstats**
This PR runs `styler::style_pkg()` with some manual tweaks to fix the most obvious code linting issues (low-hanging fruit) reported by the new GitHub Actions workflow in `R/`, `vignettes/`, and `inst/`.

This reduced 6352 issues to 2241 issues. Although there are still remaining issues to be fixed, this would be a start.

### CODE REVIEW

**Comment by LittleBeannie** [comment]
Is it okay for me to merge without all CMD check passed?

**Comment by nanxstats** [comment]
> Is it okay for me to merge without all CMD check passed?

Ah sorry, I will add follow-up commits to address the `R CMD build` issues. They do need to pass.

The lintr workflow doesn't have to pass before we can fix most of the identified linting issues.

**Comment by nanxstats** [comment]
@LittleBeannie ok, now all `R CMD check` workflows have passed. You can merge this. It was a typo in the roxygen2 tags.

### What's next

I will look into why the styler workflow (pull_request) is always failing.

For the lintr workflow, some incoming improvements:

- I will send another PR to exclude `inst/` and exclude the linter `no visible global function definition`.
- This should reduce the number of `warning` type issues substantially, making the rest `warning` issues easier to target.
- After `warning` issues are all fixed, we can then focus on the `style` type issues.

**Comment by LittleBeannie** [comment]
> @LittleBeannie ok, now all `R CMD check` workflows have passed. You can merge this. It was a typo in the roxygen2 tags.
> 
> ### What's next
> I will look into why the styler workflow (pull_request) is always failing.
> 
> For the lintr workflow, some incoming improvements:
> 
> * I will send another PR to exclude `inst/` and exclude the linter `no visible global function definition`.
> * This should reduce the number of `warning` type issues substantially, making the rest `warning` issues easier to target.
> * After `warning` issues are all fixed, we can then focus on the `style` type issues.

Thanks!

**Pull request merged**
