### PR TITLE
re-org vignettes and references

### LINKED ISSUE #341: Re-organize the pkgdown website
1. Change the virtical alignment to horizontion by sharing the same rdname fixed_Design
 image
2. move the vignette usage-gs-spending-bound.Rmd to the section of spending function.

### PR DESCRIPTION
**Pull request by LittleBeannie**
Closes #341

### CODE REVIEW

**Comment by nanxstats** [comment]
`story-test-types.Rmd` would be a more standard and evergreen name compared to `story-seven-test-type.Rmd`.

**Comment by LittleBeannie** [comment]
> `story-test-types.Rmd` would be a more standard and evergreen name compared to `story-seven-test-type.Rmd`.

Thanks for the suggestion! It has been corrected.

**Comment by nanxstats** [comment]
> > `story-test-types.Rmd` would be a more standard and evergreen name compared to `story-seven-test-type.Rmd`.
> 
> Thanks for the suggestion! It has been corrected.

Can we remove the "seven"? I mean, unless this is a special number that needs to be emphasized or you're certain that there won't be more or fewer test types defined in the future. Not mentioning the number will make the name evergreen.

**Comment by LittleBeannie** [comment]
> > > `story-test-types.Rmd` would be a more standard and evergreen name compared to `story-seven-test-type.Rmd`.
> > 
> > 
> > Thanks for the suggestion! It has been corrected.
> 
> Can we remove the "seven"? I mean, unless this is a special number that needs to be emphasized or you're certain that there won't be more or fewer test types defined in the future. Not mentioning the number will make the name evergreen.
Let's keep seven for now; I guess there is a probability of having a test.type >7 in the future.

**Review by nanxstats — CHANGES_REQUESTED** [review]
Sure! I'm ok with keeping `seven` in the file name.

Now, please take a look at the `fixed_design.html` generated by pkgdown. The information displayed there could use more structure. All very minor issues but would be great to resolve within this PR.

- The title should be (much) shorter.
- The description from all previous separate functions are becoming repetitive (although with some useful function-specific information).
- Return value is "A table" repeated 8 times.
- Code examples for different functions could use clearer separation. Maybe use comments with four trailing dashes (`----`) to mark the [code sections](https://support.posit.co/hc/en-us/articles/200484568-Code-Folding-and-Sections-in-the-RStudio-IDE#:~:text=and%20re%2Dopened.-,Code%20Sections,-Code%20sections%20allow).

I think we can merge after these minor details are improved.

**Comment by LittleBeannie** [comment]
> Sure! I'm ok with keeping `seven` in the file name.
> 
> Now, please take a look at the `fixed_design.html` generated by pkgdown. The information displayed there could use more structure. All very minor issues but would be great to resolve within this PR.
> 
> * The title should be (much) shorter.
> * The description from all previous separate functions are becoming repetitive (although with some useful function-specific information).
> * Return value is "A table" repeated 8 times.
> * Code examples for different functions could use clearer separation. Maybe use comments with four trailing dashes (`----`) to mark the [code sections](https://support.posit.co/hc/en-us/articles/200484568-Code-Folding-and-Sections-in-the-RStudio-IDE#:~:text=and%20re%2Dopened.-,Code%20Sections,-Code%20sections%20allow).
> 
> I think we can merge after these minor details are improved.

Thank you for providing valuable suggestions @nanxstats . I have addressed them in my latest commit, and I hope it effectively addresses your comments. If there are any areas that remain unclear or require further improvements in writing, please feel free to edit and commit accordingly.

**Review by nanxstats — APPROVED** [review]
Great! I finetuned the format a bit and now this looks clean ✨

**Pull request merged**
