### PR TITLE
Remove summary.gs_update()

### PR DESCRIPTION
**Pull request by jdblischak**
I started investigating the `summary()` functions for #282. I noticed that the code and documentation for `summary.gs_update()` were essentially identical to `summary.gs_design()`. When I put the documentation and functions in their own separate files and `diff`'d, the only differences were the function name and some stylistic line break differences.

```sh
$ diff R/summary.gs_design.R R/summary.gs_update.R
1c1
< summary.gs_design <- function(object,
---
> summary.gs_update <- function(object,
278,279c278
<       mutate(col_vars = dplyr::if_else(col_vars == "~risk difference at bound",
<                                        "~Risk difference at bound", col_vars
---
>       mutate(col_vars = dplyr::if_else(col_vars == "~risk difference at bound", "~Risk difference at bound", col_vars
285,286c284
<       mutate(col_vars = dplyr::if_else(col_vars == "~hr at bound",
<                                        "~HR at bound", col_vars
---
>       mutate(col_vars = dplyr::if_else(col_vars == "~hr at bound", "~HR at bound", col_vars
292,293c290
<       mutate(col_vars = dplyr::if_else(col_vars == "~whr at bound",
<                                        "~wHR at bound", col_vars
---
>       mutate(col_vars = dplyr::if_else(col_vars == "~whr at bound", "~wHR at bound", col_vars
```

This also resulted in the example code being duplicated in the help file, which you can currently observe in the [pkgdown site](https://merck.github.io/gsDesign2/reference/summary.html).

I removed this duplicated documentation and code by having `summary.gs_update()` call `summary.gs_design()`

### CODE REVIEW

**Comment by nanxstats** [comment]
Avoiding duplication is obviously essential and encouraged, but I wonder if the duplication was intentional in this context for some reasons. So I will let @LittleBeannie decide.

**Comment by LittleBeannie** [comment]
It looks `summary.gs_design` is never used, shall we directly remove it?

**Comment by jdblischak** [comment]
> It looks `summary.gs_design` is never used, shall we directly remove it?

`summary.gs_design()` is required for the tests in `test-independent_as_gt.R` to pass.

https://github.com/Merck/gsDesign2/blob/322ec8762234e6b1234dc98467190d4cbdefd64a/tests/testthat/test-independent_as_gt.R#L111-L120

This is because the result of `gs_design_ahr()` has class `"gs_design"`, and thus running `summary()` on it calls `summary.gs_design()`

```R
library("gsDesign2")

x <- gs_design_ahr()
class(x)
## [1] "non_binding" "ahr"         "gs_design"   "list"  
summary(x)
## # A tibble: 1 × 7
## # Groups:   Analysis [1]
##   Analysis              Bound     Z `~HR at bound` `Nominal p` `Alternate hypothesis` `Null hypothesis`
##   <chr>                 <chr> <dbl>          <dbl>       <dbl>                  <dbl>             <dbl>
## 1 Analysis: 1 Time: 36… Effi…  1.96          0.795       0.025                    0.9             0.025
```

**Comment by jdblischak** [comment]
However, I think we can probably remove `summary.gs_update()`. I confirmed that `R CMD check` still passes when it is deleted. It also seems unnecessary since no object is assigned the class `"gs_update"`. The objects returned by `gs_update_ahr()` still have class `"gs_design"`

```R
library(gsDesign)
library(gsDesign2)
library(dplyr)

alpha <- 0.025
beta <- 0.1
ratio <- 1

# Enrollment
enroll_rate <- define_enroll_rate(
  duration = c(2, 2, 10),
  rate = (1:3) / 3)

# Failure and dropout
fail_rate <- define_fail_rate(
  duration = c(3, Inf), fail_rate = log(2) / 9,
  hr = c(1, 0.6), dropout_rate = .0001)

# IA and FA analysis time
analysis_time <- c(20, 36)

# Randomization ratio
ratio <- 1

# Example A: one-sided design (efficacy only) ----

# Original design
upper <- gs_spending_bound
upar <- list(sf = sfLDOF, total_spend = alpha)
x <- gs_design_ahr(
  enroll_rate = enroll_rate, fail_rate = fail_rate,
  alpha = alpha, beta = beta, ratio = ratio,
  info_scale = "h0_info",
  info_frac = NULL,
  analysis_time = c(20, 36),
  upper = gs_spending_bound, upar = upar,
  lower = gs_b, lpar = rep(-Inf, 2),
  test_upper = TRUE, test_lower = FALSE) |> to_integer()

# Observed dataset at IA and FA
set.seed(123)

observed_data <- simtrial::sim_pw_surv(
  n = x$analysis$n[x$analysis$analysis == 2],
  stratum = data.frame(stratum = "All", p = 1),
  block = c(rep("control", 2), rep("experimental", 2)),
  enroll_rate = x$enroll_rate,
  fail_rate = (fail_rate |> simtrial::to_sim_pw_surv())$fail_rate,
  dropout_rate = (fail_rate |> simtrial::to_sim_pw_surv())$dropout_rate)

observed_data_ia <- observed_data |> simtrial::cut_data_by_date(x$analysis$time[1])
observed_data_fa <- observed_data |> simtrial::cut_data_by_date(x$analysis$time[2])

# Example A1 ----
# IA spending = observed events / final planned events
x_updated <- gs_update_ahr(
  x = x,
  ia_alpha_spending = "actual_info_frac",
  fa_alpha_spending = "full_alpha",
  observed_data = list(observed_data_ia, observed_data_fa))

class(x_updated)
## [1] "non_binding"    "ahr"            "gs_design"      "list"           "updated_design"
summary(x_updated)
## # A tibble: 4 × 7
## # Groups:   Analysis [2]
##   Analysis            Bound       Z `~HR at bound` `Nominal p` `Alternate hypothesis` `Null hypothesis`
##   <chr>               <chr>   <dbl>          <dbl>       <dbl>                  <dbl>             <dbl>
## 1 Analysis: 1 Time: … Futi… -Inf           Inf          1                       0                0     
## 2 Analysis: 1 Time: … Effi…    2.59          0.686      0.0048                  0.315            0.0048
## 3 Analysis: 2 Time: … Futi… -Inf           Inf          1                       0                0     
## 4 Analysis: 2 Time: … Effi…    1.99          0.794      0.0235                  0.901            0.025 
```

So the essential question is: do the summaries of the results from `gs_design_ahr()` and `gs_update_ahr()` ever need to be processed differently? If no, then we can remove the redundant function.

**Comment by LittleBeannie** [comment]
Sorry, I mean `summary.gs_update`.

**Comment by jdblischak** [comment]
As discussed above, I updated the PR to remove `summary.gs_update()`.

Documenting the decision. First, there are no objects in this package with the class `"gs_update"`. The function that would be expected to produce objects of this class, `gs_update_ahr()`, instead assigns the class `"updated_design"`.

https://github.com/Merck/gsDesign2/blob/322ec8762234e6b1234dc98467190d4cbdefd64a/R/gs_update_ahr.R#L322

Second, we could have changed the name from `summary.gs_update()` to `summary.updated_design()`. However, this is unnecessary since the object returned by `gs_update_ahr()` maintains the class `"gs_design"`, and thus is already properly routed to `summary.gs_design()` without needing an extra S3 method to redirect it.

**Review by LittleBeannie — APPROVED** [review]
Thanks!

**Pull request merged**
