### PR TITLE
update DESCRIPTION

### PR DESCRIPTION
**Pull request by elong0527**
- bump to development version.
- update authorship
- update description by using README file information.

### CODE REVIEW

**Comment by elong0527** [comment]
We need to align #54, before merge this PR.

**Comment by fb-elong** [comment]
Is this the right commit for v0.1.0 389aed0085d9430ff0c42e49b0fc0911d8da3d85? 

We probably need to complete two things for a proper NEWS file:

1. create a release for v0.1.0 
2. create a PR to compare change between v0.1.0 and v0.2.0 tag. 
3. draft NEWS based on the difference.

**Comment by LittleBeannie** [comment]
> Is this the right commit for v0.1.0 [389aed0](https://github.com/Merck/gsDesign2/commit/389aed0085d9430ff0c42e49b0fc0911d8da3d85)?
> 
> We probably need to complete few things for a proper NEWS file:
> 
> 1. create a release for v0.1.0
> 2. create a PR to compare change between v0.1.0 and v0.2.0 tag.
> 3. draft NEWS based on the difference.
> 
> It might be better to merge this PR and handle the NEWS update in a separate PR. If so, let's move the comment as an issue.
> 
> cc: @nanxstats

I think so, since May 2021 only have one commit history.

**Comment by LittleBeannie** [comment]
> > Is this the right commit for v0.1.0 [389aed0](https://github.com/Merck/gsDesign2/commit/389aed0085d9430ff0c42e49b0fc0911d8da3d85)?
> > We probably need to complete few things for a proper NEWS file:
> > 
> > 1. create a release for v0.1.0
> > 2. create a PR to compare change between v0.1.0 and v0.2.0 tag.
> > 3. draft NEWS based on the difference.
> > 
> > It might be better to merge this PR and handle the NEWS update in a separate PR. If so, let's move the comment as an issue.
> > cc: @nanxstats
> 
> I think so, since May 2021 only have one commit history.

Oops, I found the May 2021 commit `389aed0` might be too old to be a release (see screenshot below). @nanxstats , do you have any tricks for this?
image

**Review by nanxstats — APPROVED** [review]

**Comment by fb-elong** [comment]
Fine with me. Let's start the exercise from future version of release :)

**Comment by LittleBeannie** [comment]
> I don't think we need to retrospectively release v0.1.0 because that's a bit too outdated and not really important, although you can tag a release via command line: https://github.com/orgs/community/discussions/23535
> 
> You should though, release v0.2.1 (the version before the "big merge" of gsDesign2 and gsdmvn). Maybe this is the commit: [7538aac](https://github.com/Merck/gsDesign2/commit/7538aac9fa2f0d818114f71ca20c0de32f5fd1bb)

A nice tricks to learn! I just created a version 0.2.1 before the big merged with `Merck/gsdmvn`.

**Pull request merged**
