### PR TITLE
fix lpar bug

### PR DESCRIPTION
**Pull request by LittleBeannie**

### CODE REVIEW

**Review by yuliasidi — COMMENTED** [review]
looks good to me

**Comment by nanxstats** [comment]
> > ```r
> > lpar, rep(-Inf, K)
> > ```
> 
> Since the logic is not 100% equivalent

I'm interested to learn why they are not equivalent - feels like I was simply flipping the conditioning order of both if-else statements. Perhaps I'm missing something?

**Comment by nanxstats** [comment]
@LittleBeannie Do you plan to make any updates? I can merge this if there is no plan to make further changes.

**Comment by LittleBeannie** [comment]
> @LittleBeannie Do you plan to make any updates? I can merge this if there is no plan to make further changes.

No, that's everything I have! But I owe you a counter-example!

**Review by nanxstats — APPROVED** [review]
Let's merge this before it's getting merge conflicts.

**Pull request merged**
