### PR TITLE
266 remove old files in inst folder

### PR DESCRIPTION
**Pull request by LittleBeannie**

### CODE REVIEW

**Review by nanxstats — CHANGES_REQUESTED** [review]
This looks great but I **really** needed two technical improvements:

1. Please encapsulate all tests in `test_that()` instead of running them in the global environment.

   ```r
   test_that("multiplication works", {
     expect_equal(...)
   })
   ```

   From <https://testthat.r-lib.org/reference/test_that.html>:

   > Each test has its own execution environment, so an object created in a test
   > also dies with the test... Avoid changing global state, when possible,
   > and reverse any changes that you do make.

2. Please make an effort to fix the 128 code linting errors.

**Comment by LittleBeannie** [comment]
> This looks great but I **really** needed two technical improvements:
> 
> 1. Please encapsulate each test in `test_that()` instead of running them in the global environment.
>    ```r
>    test_that("multiplication works", {
>      expect_equal(...)
>    })
>    ```
>    
>    
>        
>          
>        
>    
>          
>        
>    
>        
>      
>    From https://testthat.r-lib.org/reference/test_that.html:
>    > Each test has its own execution environment, so an object created in a test
>    > also dies with the test... Avoid changing global state, when possible,
>    > and reverse any changes that you do make.
> 2. Please make an effort to fix the 128 code linting errors.

Good points! This is still a working PR and is not ready for review yet. For the lintr issue with "Trailing whitespace", is it possible we can automatically enable delete these trailing whitespace?

**Comment by nanxstats** [comment]
> Good points! This is still a working PR and is not ready for review yet. For the lintr issue with "Trailing whitespace", is it possible we can automatically enable delete these trailing whitespace?

Of course, there are a few options to remove trailing whitespaces semi-automatically:

1. RStudio has an editor option:
   Tools -> Global Options -> Code -> Saving -> Strip trailing horizontal whitespace when saving.
3. Running styler on the file or package can often remove the trailing whitespaces.
4. Use VS Code extension "Trailing Spaces" which has a command to "Trim Trailing Whitespace".

**Comment by LittleBeannie** [comment]
> > Good points! This is still a working PR and is not ready for review yet. For the lintr issue with "Trailing whitespace", is it possible we can automatically enable delete these trailing whitespace?
> 
> Of course, there are a few options to remove trailing whitespaces semi-automatically:
> 
> 1. RStudio has an editor option:
>    Tools -> Global Options -> Code -> Saving -> Strip trailing horizontal whitespace when saving.
> 2. Running styler on the file or package can often remove the trailing whitespaces.
> 3. Use VS Code extension "Trailing Spaces" which has a command to "Trim Trailing Whitespace".

Is it possible if  enable these operations into the workflow as automatic commits?

**Comment by LittleBeannie** [comment]
Ready for review now

**Review by nanxstats — APPROVED** [review]
Looks great! I appreciate the efforts put into the proper testthat encapsulation and fixing the code linting issues.

**Pull request merged**
